import './globals.css'
import { Inter } from 'next/font/google'
import GlobalContextProvider from './state/context/GlobalContext'
import { Toaster } from 'react-hot-toast'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <GlobalContextProvider>
      <body className={inter.className}>{children}</body>
      <Toaster/>
      </GlobalContextProvider>
      
    </html>
  )
}
